<script setup lang="ts">
import type { RecipeDraft } from '~/types/api'
const api = useApi(); const message = ref(''); const servings = ref(4); const recipe = ref<RecipeDraft | null>(null); const busy = ref(false); const notice = ref(''); const loginEmail = ref('admin@example.invalid'); const loginPassword = ref('change-me-before-first-start'); const recorder = ref<MediaRecorder | null>(null)
async function login() { notice.value = ''; try { await api.login(loginEmail.value, loginPassword.value); notice.value = 'Angemeldet.' } catch { notice.value = 'Anmeldung fehlgeschlagen.' } }
async function generate() { if (message.value.trim().length < 3) { notice.value = 'Bitte beschreibe das gewünschte Rezept.'; return } busy.value=true; notice.value='Rezept wird entworfen …'; try { recipe.value = await api.generate(message.value, servings.value); notice.value='Entwurf bereit.' } catch { notice.value='Rezeptentwurf fehlgeschlagen.' } finally { busy.value=false } }
async function record() { if (!navigator.mediaDevices) { notice.value='Spracheingabe wird nicht unterstützt.'; return } if (recorder.value) { recorder.value.stop(); return } const stream=await navigator.mediaDevices.getUserMedia({audio:true}); const chunks: BlobPart[]=[]; const value=new MediaRecorder(stream); value.ondataavailable=(event)=>chunks.push(event.data); value.onstop=async()=>{stream.getTracks().forEach(track=>track.stop()); recorder.value=null; notice.value='Transkribiere …'; try { message.value=(await api.transcribe(new Blob(chunks,{type:value.mimeType}))).text; notice.value='Transkription eingefügt.' } catch { notice.value='Transkription fehlgeschlagen.' }}; value.start(); recorder.value=value; notice.value='Aufnahme läuft – erneut klicken zum Beenden.' }
async function publish(withImage: boolean) { if (!recipe.value) return; notice.value='Speichere in Mealie …'; try { const result=await api.publish(recipe.value,withImage); notice.value=`In Mealie gespeichert: ${result.slug}${result.image_status === 'uploaded' ? ' (Bild hochgeladen)' : ''}` } catch { notice.value='Mealie-Speicherung fehlgeschlagen. Konfiguration prüfen.' } }
</script>
<template><main><header class="top"><div><span class="eyebrow">MEALIE · REZEPTASSISTENT</span><h1>Idee rein. Rezept raus.</h1></div><button v-if="api.user.value" class="logout" @click="api.logout">Abmelden</button></header><section v-if="!api.user.value" class="login panel"><h2>Anmelden</h2><form @submit.prevent="login"><input v-model="loginEmail" type="email" required aria-label="E-Mail"><input v-model="loginPassword" type="password" required aria-label="Passwort"><button>Anmelden</button></form><p>Die voreingestellten Daten sind ausschließlich für den ersten lokalen Start gedacht.</p></section><template v-else><section class="panel composer"><label for="prompt">Was möchtest du kochen?</label><div class="prompt"><textarea id="prompt" v-model="message" rows="4" placeholder="Schnelles vegetarisches Gericht mit Kichererbsen, mild, für die Familie"></textarea><button class="mic" :class="{recording:recorder}" @click="record">{{ recorder ? '■' : '●' }}</button></div><div class="actions"><label>Personen <input v-model.number="servings" type="number" min="1" max="100"></label><button :disabled="busy" @click="generate">{{ busy ? 'Entwirft …' : 'Rezept entwerfen' }}</button></div></section><p class="notice">{{ notice }}</p><RecipeDraft v-if="recipe" :recipe="recipe" @publish="publish"/><UserManagement v-if="api.user.value.is_admin"/></template></main></template>
<style scoped>main{max-width:1050px;margin:0 auto;padding:3.5rem 1.25rem 5rem}.top{display:flex;justify-content:space-between;align-items:start;margin-bottom:2rem}.eyebrow{font-size:.75rem;letter-spacing:.12em;font-weight:850;color:#dc661b}.top h1{font-size:clamp(2.3rem,6vw,4.5rem);letter-spacing:-.065em;line-height:.95;margin:.35rem 0}.panel{background:#fff;border:1px solid #e1e7ef;border-radius:20px;padding:1.5rem;box-shadow:0 16px 40px #18253d0a}.composer>label{font-weight:800}.prompt{display:flex;gap:.7rem;margin:.7rem 0}.prompt textarea{width:100%;border:1px solid #c8d2df;border-radius:11px;padding:.8rem;resize:vertical}.mic{border:0;background:#fde6dc;color:#c64e0b;border-radius:10px;padding:0 1rem;font-weight:800}.mic.recording{background:#b42318;color:#fff}.actions{display:flex;justify-content:space-between;align-items:center}.actions label{font-weight:700}.actions input{width:4.6rem;margin-left:.4rem;padding:.45rem;border:1px solid #c8d2df;border-radius:8px}.actions button,.login button{border:0;border-radius:9px;background:#17263c;color:#fff;padding:.7rem 1rem;font-weight:800}.notice{min-height:1.5rem;color:#536274;font-weight:650}.login{max-width:600px}.login form{display:flex;gap:.6rem}.login input{min-width:0;flex:1;padding:.65rem;border:1px solid #c8d2df;border-radius:8px}.login p{font-size:.85rem;color:#657487}.logout{border:1px solid #c8d2df;background:#fff;border-radius:8px;padding:.5rem .7rem}@media(max-width:600px){main{padding-top:2rem}.top,.actions,.login form{flex-direction:column;align-items:stretch}.top h1{font-size:2.7rem}.actions button{margin-top:1rem}}</style>
